version: "3"

services:
  web:
    build: .
    image: antoninacr.azurecr.io/django-acr:v1
    platform: linux/amd64
    #command: bash -c "python project/manage.py makemigrations && python project/manage.py migrate && python project/manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"

    