version: "3"

services:
  web:
    build: .
    image: antoninacr.azurecr.io/django-acr:v1
    platform: linux/amd64
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"